# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SnsLoginFeature' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'GoogleSignIn'
 pod 'FBSDKLoginKit'
 pod 'FacebookCore'
 pod 'FacebookLogin'
 pod 'FacebookSDK'
 pod 'TwitterKit'
 pod 'YJLoginSDK',  '~> 0.1'
end
